/*
 * IriusRisk API
 * Products API
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.restapi.client.api;

import com.iriusrisk.restapi.client.ApiException;
import com.iriusrisk.restapi.client.model.Error;
import java.io.File;
import com.iriusrisk.restapi.client.model.InlineResponse2001;
import com.iriusrisk.restapi.client.model.InlineResponse2011;
import com.iriusrisk.restapi.client.model.UpdateStatusTestRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestsApi
 */
@Ignore
public class TestsApiTest {

    private final TestsApi api = new TestsApi();

    
    /**
     * Updates a single test to a component.
     *
     * Updates a single test to a component. Conditions to be able to perform the action:   - To have the permission **TEST_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsRefComponentsComponentRefTestsCwePutTest() throws ApiException {
        String apiToken = null;
        String ref = null;
        String componentRef = null;
        String cwe = null;
        UpdateStatusTestRequestBody updateStatusTestRequestBody = null;
        List<InlineResponse2001> response = api.productsRefComponentsComponentRefTestsCwePut(apiToken, ref, componentRef, cwe, updateStatusTestRequestBody);

        // TODO: test validations
    }
    
    /**
     * Imports test results from different sources to a component
     *
     * Imports test results from different sources (OWASP ZAP, Cucumber, Micro Focus Fortify) into the specified component. More than one file can be attached to the call. Conditions to be able to perform the action:   - To have the permission **TEST_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsRefComponentsComponentRefTestsTestTypeUploadPostTest() throws ApiException {
        String apiToken = null;
        String ref = null;
        String componentRef = null;
        String testType = null;
        File fileName = null;
        InlineResponse2011 response = api.productsRefComponentsComponentRefTestsTestTypeUploadPost(apiToken, ref, componentRef, testType, fileName);

        // TODO: test validations
    }
    
    /**
     * Imports test results from different sources to a product.
     *
     * Imports test results from different sources (OWASP ZAP, Cucumber, Micro Focus Fortify) uploading files. More than one file can be attached to the call. Conditions to be able to perform the action:   - To have the permission **TEST_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsRefTestsTestTypeUploadPostTest() throws ApiException {
        String apiToken = null;
        String ref = null;
        String testType = null;
        File fileName = null;
        InlineResponse2011 response = api.productsRefTestsTestTypeUploadPost(apiToken, ref, testType, fileName);

        // TODO: test validations
    }
    
}
