/*
 * IriusRisk API
 * Products API
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.restapi.client.api;

import com.iriusrisk.restapi.client.ApiException;
import com.iriusrisk.restapi.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokenApi
 */
@Ignore
public class TokenApiTest {

    private final TokenApi api = new TokenApi();

    
    /**
     * Generates a user API token
     *
     * Generates a new user API token. If the user already has a generated API token, generates a new one. Conditions to be able to perform the action:   - To have the permission **ALL_USERS_UPDATE** granted, or   - To have the permission **MANAGE_USERS_BU** granted. Having this permission you can generate a user API token to users who belongs to some of your user groups. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersUsernameTokenPostTest() throws ApiException {
        String apiToken = null;
        String username = null;
        String response = api.usersUsernameTokenPost(apiToken, username);

        // TODO: test validations
    }
    
}
