/*
 * IriusRisk API
 * Products API
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ArchitectureDiagram
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-15T08:48:15.539+01:00")



public class ArchitectureDiagram {
  @JsonProperty("draft")
  private Boolean draft = null;

  @JsonProperty("schema")
  private String schema = null;

  public ArchitectureDiagram draft(Boolean draft) {
    this.draft = draft;
    return this;
  }

   /**
   * Get draft
   * @return draft
  **/
  @ApiModelProperty(value = "")
  public Boolean isDraft() {
    return draft;
  }

  public void setDraft(Boolean draft) {
    this.draft = draft;
  }

  public ArchitectureDiagram schema(String schema) {
    this.schema = schema;
    return this;
  }

   /**
   * The representation of the architecture diagram in Draw.io XML format encoded in Base64
   * @return schema
  **/
  @ApiModelProperty(value = "The representation of the architecture diagram in Draw.io XML format encoded in Base64")
  public String getSchema() {
    return schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchitectureDiagram architectureDiagram = (ArchitectureDiagram) o;
    return Objects.equals(this.draft, architectureDiagram.draft) &&
        Objects.equals(this.schema, architectureDiagram.schema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(draft, schema);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchitectureDiagram {\n");
    
    sb.append("    draft: ").append(toIndentedString(draft)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

