/*
 * IriusRisk API
 * IriusRisk provides this featured API to allow for deeper customer integrations as well as enable very flexible automations within the many varied environments IriusRisk needs to operate.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.api.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * ControlsId
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-04T10:27:59.154+01:00")
public class ControlsId {
  @JsonProperty("controlsId")
  private List<BigDecimal> controlsId = null;

  public ControlsId controlsId(List<BigDecimal> controlsId) {
    this.controlsId = controlsId;
    return this;
  }

  public ControlsId addControlsIdItem(BigDecimal controlsIdItem) {
    if (this.controlsId == null) {
      this.controlsId = new ArrayList<BigDecimal>();
    }
    this.controlsId.add(controlsIdItem);
    return this;
  }

   /**
   * List of countermeassures ids to delete
   * @return controlsId
  **/
  @ApiModelProperty(value = "List of countermeassures ids to delete")
  public List<BigDecimal> getControlsId() {
    return controlsId;
  }

  public void setControlsId(List<BigDecimal> controlsId) {
    this.controlsId = controlsId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControlsId controlsId = (ControlsId) o;
    return Objects.equals(this.controlsId, controlsId.controlsId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controlsId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControlsId {\n");
    
    sb.append("    controlsId: ").append(toIndentedString(controlsId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

