/*
 * IriusRisk API
 * Products API
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-15T08:48:15.539+01:00")



public class InlineResponse200 {
  @JsonProperty("unassigned")
  private List<String> unassigned = null;

  @JsonProperty("notFound")
  private List<String> notFound = null;

  public InlineResponse200 unassigned(List<String> unassigned) {
    this.unassigned = unassigned;
    return this;
  }

  public InlineResponse200 addUnassignedItem(String unassignedItem) {
    if (this.unassigned == null) {
      this.unassigned = new ArrayList<String>();
    }
    this.unassigned.add(unassignedItem);
    return this;
  }

   /**
   * Get unassigned
   * @return unassigned
  **/
  @ApiModelProperty(value = "")
  public List<String> getUnassigned() {
    return unassigned;
  }

  public void setUnassigned(List<String> unassigned) {
    this.unassigned = unassigned;
  }

  public InlineResponse200 notFound(List<String> notFound) {
    this.notFound = notFound;
    return this;
  }

  public InlineResponse200 addNotFoundItem(String notFoundItem) {
    if (this.notFound == null) {
      this.notFound = new ArrayList<String>();
    }
    this.notFound.add(notFoundItem);
    return this;
  }

   /**
   * Get notFound
   * @return notFound
  **/
  @ApiModelProperty(value = "")
  public List<String> getNotFound() {
    return notFound;
  }

  public void setNotFound(List<String> notFound) {
    this.notFound = notFound;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.unassigned, inlineResponse200.unassigned) &&
        Objects.equals(this.notFound, inlineResponse200.notFound);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unassigned, notFound);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    unassigned: ").append(toIndentedString(unassigned)).append("\n");
    sb.append("    notFound: ").append(toIndentedString(notFound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

