/*
 * IriusRisk API
 * IriusRisk provides this featured API to allow for deeper customer integrations as well as enable very flexible automations within the many varied environments IriusRisk needs to operate.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.api.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RiskCount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-04T10:27:59.154+01:00")
public class RiskCount {
  @JsonProperty("mitigated")
  private Integer mitigated = null;

  @JsonProperty("low")
  private Integer low = null;

  @JsonProperty("medium")
  private Integer medium = null;

  @JsonProperty("high")
  private Integer high = null;

  @JsonProperty("critical")
  private Integer critical = null;

  public RiskCount mitigated(Integer mitigated) {
    this.mitigated = mitigated;
    return this;
  }

   /**
   * Get mitigated
   * @return mitigated
  **/
  @ApiModelProperty(value = "")
  public Integer getMitigated() {
    return mitigated;
  }

  public void setMitigated(Integer mitigated) {
    this.mitigated = mitigated;
  }

  public RiskCount low(Integer low) {
    this.low = low;
    return this;
  }

   /**
   * Get low
   * @return low
  **/
  @ApiModelProperty(value = "")
  public Integer getLow() {
    return low;
  }

  public void setLow(Integer low) {
    this.low = low;
  }

  public RiskCount medium(Integer medium) {
    this.medium = medium;
    return this;
  }

   /**
   * Get medium
   * @return medium
  **/
  @ApiModelProperty(value = "")
  public Integer getMedium() {
    return medium;
  }

  public void setMedium(Integer medium) {
    this.medium = medium;
  }

  public RiskCount high(Integer high) {
    this.high = high;
    return this;
  }

   /**
   * Get high
   * @return high
  **/
  @ApiModelProperty(value = "")
  public Integer getHigh() {
    return high;
  }

  public void setHigh(Integer high) {
    this.high = high;
  }

  public RiskCount critical(Integer critical) {
    this.critical = critical;
    return this;
  }

   /**
   * Get critical
   * @return critical
  **/
  @ApiModelProperty(value = "")
  public Integer getCritical() {
    return critical;
  }

  public void setCritical(Integer critical) {
    this.critical = critical;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskCount riskCount = (RiskCount) o;
    return Objects.equals(this.mitigated, riskCount.mitigated) &&
        Objects.equals(this.low, riskCount.low) &&
        Objects.equals(this.medium, riskCount.medium) &&
        Objects.equals(this.high, riskCount.high) &&
        Objects.equals(this.critical, riskCount.critical);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mitigated, low, medium, high, critical);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskCount {\n");
    
    sb.append("    mitigated: ").append(toIndentedString(mitigated)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    critical: ").append(toIndentedString(critical)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

