/*
 * IriusRisk API
 * IriusRisk provides this featured API to allow for deeper customer integrations as well as enable very flexible automations within the many varied environments IriusRisk needs to operate.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.api.client;

import com.iriusrisk.api.client.model.RiskSummary;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for RisksApi
 */
@Ignore
public class RisksApiTest {

    private final RisksApi api = new RisksApi();

    
    /**
     * Gets the risks summary of a product
     *
     * This endpoint returns a summary of the risks of a product. Conditions to be able to perform the action:   - No permissions are required to perform this action. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsProductIdRisksGetTest() {
        String productId = null;
        RiskSummary response = api.productsProductIdRisksGet(productId);

        // TODO: test validations
    }
    
}
