/*
 * IriusRisk API
 * IriusRisk provides this featured API to allow for deeper customer integrations as well as enable very flexible automations within the many varied environments IriusRisk needs to operate.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.iriusrisk.api.client;

import com.iriusrisk.api.client.model.Body11;
import com.iriusrisk.api.client.model.Body14;
import com.iriusrisk.api.client.model.Body15;
import com.iriusrisk.api.client.model.Body16;
import com.iriusrisk.api.client.model.LibraryControl;
import com.iriusrisk.api.client.model.LibraryUseCase;
import com.iriusrisk.api.client.model.LibraryWeakness;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for UseCasesApi
 */
@Ignore
public class UseCasesApiTest {

    private final UseCasesApi api = new UseCasesApi();

    
    /**
     * Creates new use case in a library.
     *
     * Creates new use case in a library. Conditions to be able to perform the action:   - To have the permission **LIBRARY_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void librariesLibraryIdRiskpatternsRiskPatternIdUsecasesPostTest() {
        String libraryId = null;
        String riskPatternId = null;
        Body11 body = null;
        LibraryUseCase response = api.librariesLibraryIdRiskpatternsRiskPatternIdUsecasesPost(libraryId, riskPatternId, body);

        // TODO: test validations
    }
    
    /**
     * Associates a countermeasure to a threat in a risk pattern.
     *
     * Associates a countermeasure to a threat in a risk pattern. Conditions to be able to perform the action:   - To have the permission **LIBRARY_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void librariesLibraryIdRiskpatternsRiskPatternIdUsecasesUseCaseIdThreatsThreatIdCountermeasuresPutTest() {
        String libraryId = null;
        String riskPatternId = null;
        String useCaseId = null;
        String threatId = null;
        Body16 body = null;
        LibraryControl response = api.librariesLibraryIdRiskpatternsRiskPatternIdUsecasesUseCaseIdThreatsThreatIdCountermeasuresPut(libraryId, riskPatternId, useCaseId, threatId, body);

        // TODO: test validations
    }
    
    /**
     * Associates weakness to a threat in a risk pattern.
     *
     * Associates weakness to a threat in a risk pattern. Conditions to be able to perform the action:   - To have the permission **LIBRARY_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void librariesLibraryIdRiskpatternsRiskPatternIdUsecasesUseCaseIdThreatsThreatIdWeaknessesPutTest() {
        String libraryId = null;
        String riskPatternId = null;
        String useCaseId = null;
        String threatId = null;
        Body14 body = null;
        LibraryWeakness response = api.librariesLibraryIdRiskpatternsRiskPatternIdUsecasesUseCaseIdThreatsThreatIdWeaknessesPut(libraryId, riskPatternId, useCaseId, threatId, body);

        // TODO: test validations
    }
    
    /**
     * Associates a countermeasure to a weakness in a risk pattern.
     *
     * Associates a countermeasure to a weakness in a risk pattern. Conditions to be able to perform the action:   - To have the permission **LIBRARY_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void librariesLibraryIdRiskpatternsRiskPatternIdUsecasesUseCaseIdThreatsThreatIdWeaknessesWeaknessIdCountermeasuresPutTest() {
        String libraryId = null;
        String riskPatternId = null;
        String useCaseId = null;
        String threatId = null;
        String weaknessId = null;
        Body15 body = null;
        LibraryControl response = api.librariesLibraryIdRiskpatternsRiskPatternIdUsecasesUseCaseIdThreatsThreatIdWeaknessesWeaknessIdCountermeasuresPut(libraryId, riskPatternId, useCaseId, threatId, weaknessId, body);

        // TODO: test validations
    }
    
}
